import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { StoreWrapper } from "../../mobx/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <StoreProvider> */}
      <body className={inter.className}>
      <StoreWrapper>
        {children}
      </StoreWrapper>
        </body>
      {/* </StoreProvider> */}
    </html>
  );
}


// import { useContext } from "react";
// import { StoreContext } from "@/store/provider";

// export const useStores = () => {
//   return useContext(StoreContext);
// };